### ISSUE TITLE
Feature order of genes on complementary strand are confusing

### ISSUE THREAD

**Issue by jcsanchez2** [CroBiAd/DAWN#1]
Feature order is shown 5' -> 3' relative to the reference, while the sequence associated with the features are reverse complemented, as expected. In addition, the feature numbering is "backwards" for these features. This will be very confusing for DAWN users.

**Comment by nathanhaigh** [comment]
I submitted a pull request to JBrowse to fix this (https://github.com/GMOD/jbrowse/pull/1114). The fix has been merged into the latest version of JBrowse (`v1.15.0`) and is now the version underpinning DAWN.
