### ISSUE TITLE
Chromosome scolling beyond limits

### ISSUE THREAD

**Issue by nathanhaigh** [CroBiAd/DAWN#7]
It is possible to scroll beyond the end of a chromosome. The end coord stays the same as the chrom end coord, but the start coord ends up being larger than the end of the chrom and the range displayed goes into negative territory.

**Comment by cmdcolin** [comment]
If you are using prepare-refseqs with indexed fasta I might have found a bug fix for this https://github.com/GMOD/jbrowse/commit/475f1f55ed6f477ec2ce40d63807e23c02d72445

**Comment by nathanhaigh** [comment]
@cmdcolin that commit will fix the issue i.e. end coordinate was being output as a string in the `refSeqs.json` file instead of an numerical. I've manually modified my `refSeqs.json` file to unquote the `end` value.
